{
  "openapi": "3.1.1",
  "info": {
    "title": "Todolist RESTful API",
    "version": "1.0",
    "description": "OpenApi for Todolist RESTful API",
    "termsOfService": "http://google.com",
    "contact": {
      "name": "Fachran Sandi",
      "email": "fachransandi@gmail.com",
      "url": "http://gmail.com"
    },
    "license": {
      "name": "APACHE 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "description": "Todolist RESTful API Server",
      "url": "http://{environment}.program.com/api/v1",
      "variables": {
        "environment": {
          "description": "Server Environment",
          "default": "dev",
          "enum": ["dev", "qa", "prod"]
        }
      }
    }
  ],
  "externalDocs": {
    "description": "Youtube Rajin",
    "url": "http://Youtube.com"
  },
  "paths": {
    "/todolist": {
      "get": {
        "tags": ["todolist"],
        "summary": "Get All Todolist",
        "description": "Only returns active todolist. Completed or deleted items are excluded.",
        "parameters": [
          {
            "name": "include_done",
            "in": "query",
            "description": "Include completed todolist entries",
            "required": false,
            "schema": {
              "type": ["boolean", "null"],
              "default": false
            }
          },
          {
            "name": "name",
            "in": "query",
            "required": false,
            "description": "Filter todolist by name",
            "schema": {
              "type": ["string", "null"],
              "minLength": 1,
              "maxLength": 100
            },
            "examples": {
              "java": {
                "description": "Example Name JAVA",
                "value": "JAVA"
              },
              "php": {
                "value": "PHP"
              }
            }
          }
        ],
        "security": [
          {
            "TodolistAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ArrayTodolist"
                },
                "examples": {
                  "success": {
                    "description": "Sample todolist",
                    "value": [
                      {
                        "id": "1",
                        "name": "java",
                        "priority": 3,
                        "tags": ["java", "programming"]
                      },
                      {
                        "id": "2",
                        "name": "PHP",
                        "priority": 4,
                        "tags": ["PHP", "programming"]
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["todolist"],
        "summary": "Create new Todolist",
        "description": "Create a new active todolist",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
              },
              "examples": {
                "java": {
                  "value": {
                    "name": "JAVA",
                    "priority": 3,
                    "tags": ["java", "programming"]
                  }
                },
                "php": {
                  "value": {
                    "name": "PHP",
                    "priority": 6,
                    "tags": ["PHP", "programming"]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully created todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "example": {
                  "id": "3",
                  "name": "JAVA",
                  "priority": 3,
                  "tags": ["java", "programming"]
                }
              }
            }
          }
        }
      }
    },
    "/todolist/{todolistId}": {
      "put": {
        "tags": ["todolist"],
        "summary": "Update existing todolist",
        "description": "Update existing todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/todolistId"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrUpdateTodolist"
              },
              "examples": {
                "java": {
                  "value": {
                    "name": "JAVA",
                    "priority": 3,
                    "tags": ["java", "programming"]
                  }
                },
                "php": {
                  "value": {
                    "name": "PHP",
                    "priority": 6,
                    "tags": ["PHP", "programming"]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully updated todolist",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Todolist"
                },
                "example": {
                  "id": "1",
                  "name": "JAVA",
                  "priority": 3,
                  "tags": ["java", "programming"]
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["todolist"],
        "summary": "Delete existing todolist",
        "description": "Delete existing todolist in database",
        "parameters": [
          {
            "$ref": "#/components/parameters/todolistId"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "success": {
                    "value": {
                      "success": true
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Failed to delete todolist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "type": "boolean"
                    }
                  }
                },
                "examples": {
                  "failed": {
                    "value": {
                      "success": false
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "TodolistAuth": {
        "description": "Auth for todolist RESTful API",
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      }
    },
    "parameters": {
      "todolistId": {
        "name": "todolistId",
        "in": "path",
        "required": true,
        "description": "Todolist ID",
        "schema": {
          "type": "string",
          "minLength": 1,
          "maxLength": 100
        },
        "examples": {
          "java": {
            "value": "1"
          },
          "php": {
            "value": "2"
          }
        }
      }
    },
    "schemas": {
      "Todolist": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "priority": {
            "type": "integer",
            "format": "int32"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": ["id", "name", "priority"]
      },
      "CreateOrUpdateTodolist": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1
          },
          "priority": {
            "type": "integer",
            "format": "int32",
            "default": 1
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string",
              "minLength": 1
            },
            "minItems": 1
          }
        },
        "required": ["name", "priority"]
      },
      "ArrayTodolist": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Todolist"
        }
      }
    }
  }
}
